### ISSUE TITLE
Unknown file type.

### ISSUE THREAD

**Issue by mrwert** [guidoreina/downloader#1]
[urls.txt]
http://ronney.usc.edu/AME101/AME101-LectureNotes.pdf
http://ronney.usc.edu/AME101/AME101-F15-PS1.pdf

I got two files (000000000000 and 000000000001).
mv 000000000000 file.pdf
Files can not be opened. [zathura] error: Unknown file type: 'application/octet-stream'.

...did i do something wrong? :)
Thanks! :)

**Comment by guidoreina** [comment]
Hi :),
All the downloaded files have a header with the format:
 `<URL>`
 `Status-Line`
 `*(message-header)`
 `<empty-line>`
 `[message-body]`

So, if you delete the first lines until and including the first empty line, you get the file you have downloaded (hopefully :) ). That is the message-body.

**Comment by mrwert** [comment]
It's working :)
Thanks!

**Comment by guidoreina** [comment]
You're welcome :)
